apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch.yaml

configMapGenerator:
  - name: env-injector-files
    namespace: CHANGE_ME  # TODO: Set target namespace for this cluster
    files:
      - sitecustomize.py
      - profiler_config.yaml

generatorOptions:
  disableNameSuffixHash: true
