apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-injector
  namespace: vllm-profiler
spec:
  template:
    spec:
      containers:
        - name: webhook
          env:
            - name: TARGET_NAMESPACE
              value: "kserve-e2e-perf"
            - name: TARGET_LABELS
              value: "component=predictor"
